version: "3"

services:
  s1:
    image: expressjs
    container_name: s1
    ports:
      - "3000:3000"
    volumes:
      - ./service1/index.js:/home/service/index.js
  s2:
    image: expressjs
    container_name: s2
    ports:
      - "3001:3000"
    volumes:
      - ./service2/index.js:/home/service/index.js

